// Code generated by protoc-gen-gogo.
// source: stores.proto
// DO NOT EDIT!

/*
Package stores is a generated protocol buffer package.

It is generated from these files:
	stores.proto

It has these top-level messages:
	CassandraParams
	CassandraTokenRange
*/
package stores

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CassandraParams struct {
	Hosts     []string `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
	Keyspace  string   `protobuf:"bytes,2,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	TableName string   `protobuf:"bytes,3,opt,name=tableName,proto3" json:"tableName,omitempty"`
}

func (m *CassandraParams) Reset()                    { *m = CassandraParams{} }
func (m *CassandraParams) String() string            { return proto.CompactTextString(m) }
func (*CassandraParams) ProtoMessage()               {}
func (*CassandraParams) Descriptor() ([]byte, []int) { return fileDescriptorStores, []int{0} }

func (m *CassandraParams) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *CassandraParams) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *CassandraParams) GetTableName() string {
	if m != nil {
		return m.TableName
	}
	return ""
}

type CassandraTokenRange struct {
	Start int64 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End   int64 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
}

func (m *CassandraTokenRange) Reset()                    { *m = CassandraTokenRange{} }
func (m *CassandraTokenRange) String() string            { return proto.CompactTextString(m) }
func (*CassandraTokenRange) ProtoMessage()               {}
func (*CassandraTokenRange) Descriptor() ([]byte, []int) { return fileDescriptorStores, []int{1} }

func (m *CassandraTokenRange) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *CassandraTokenRange) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func init() {
	proto.RegisterType((*CassandraParams)(nil), "stores.CassandraParams")
	proto.RegisterType((*CassandraTokenRange)(nil), "stores.CassandraTokenRange")
}

func init() { proto.RegisterFile("stores.proto", fileDescriptorStores) }

var fileDescriptorStores = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x44, 0xce, 0xb1, 0x0a, 0xc2, 0x30,
	0x10, 0x80, 0x61, 0x62, 0xb0, 0xd8, 0x43, 0x50, 0xa2, 0x43, 0x10, 0x87, 0xd2, 0xa9, 0x93, 0x8b,
	0xb3, 0x93, 0xbb, 0x48, 0xf0, 0x05, 0xae, 0xf6, 0x50, 0xa8, 0x4d, 0x4a, 0xee, 0x16, 0xdf, 0x5e,
	0x9a, 0x40, 0xdd, 0xee, 0xbb, 0x1b, 0xfe, 0x83, 0x35, 0x4b, 0x88, 0xc4, 0xa7, 0x31, 0x06, 0x09,
	0xa6, 0xc8, 0xaa, 0x11, 0x36, 0x57, 0x64, 0x46, 0xdf, 0x45, 0xbc, 0x63, 0xc4, 0x81, 0xcd, 0x1e,
	0x96, 0xef, 0xc0, 0xc2, 0x56, 0x55, 0xba, 0x29, 0x5d, 0x86, 0x39, 0xc0, 0xaa, 0xa7, 0x2f, 0x8f,
	0xf8, 0x24, 0xbb, 0xa8, 0x54, 0x53, 0xba, 0xd9, 0xe6, 0x08, 0xa5, 0x60, 0xfb, 0xa1, 0x1b, 0x0e,
	0x64, 0x75, 0x3a, 0xfe, 0x17, 0xf5, 0x05, 0x76, 0x73, 0xe2, 0x11, 0x7a, 0xf2, 0x0e, 0xfd, 0x8b,
	0xa6, 0x0c, 0x0b, 0x46, 0xb1, 0xaa, 0x52, 0x8d, 0x76, 0x19, 0x66, 0x0b, 0x9a, 0x7c, 0x97, 0x0a,
	0xda, 0x4d, 0x63, 0x5b, 0xa4, 0x87, 0xcf, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x25, 0xce, 0x2d,
	0x83, 0xc0, 0x00, 0x00, 0x00,
}
