// Code generated by protoc-gen-gogo.
// source: shortestPath.proto
// DO NOT EDIT!

/*
Package shortestPath is a generated protocol buffer package.

It is generated from these files:
	shortestPath.proto

It has these top-level messages:
	ShortestPathMessage
*/
package shortestPath

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ShortestPathMessage struct {
	PathLength int64 `protobuf:"varint,1,opt,name=pathLength,proto3" json:"pathLength,omitempty"`
}

func (m *ShortestPathMessage) Reset()                    { *m = ShortestPathMessage{} }
func (m *ShortestPathMessage) String() string            { return proto.CompactTextString(m) }
func (*ShortestPathMessage) ProtoMessage()               {}
func (*ShortestPathMessage) Descriptor() ([]byte, []int) { return fileDescriptorShortestPath, []int{0} }

func (m *ShortestPathMessage) GetPathLength() int64 {
	if m != nil {
		return m.PathLength
	}
	return 0
}

func init() {
	proto.RegisterType((*ShortestPathMessage)(nil), "shortestPath.ShortestPathMessage")
}

func init() { proto.RegisterFile("shortestPath.proto", fileDescriptorShortestPath) }

var fileDescriptorShortestPath = []byte{
	// 90 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0xce, 0xc8, 0x2f,
	0x2a, 0x49, 0x2d, 0x2e, 0x09, 0x48, 0x2c, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2,
	0x41, 0x16, 0x53, 0x32, 0xe5, 0x12, 0x0e, 0x46, 0xe2, 0xfb, 0xa6, 0x16, 0x17, 0x27, 0xa6, 0xa7,
	0x0a, 0xc9, 0x71, 0x71, 0x15, 0x24, 0x96, 0x64, 0xf8, 0xa4, 0xe6, 0xa5, 0x97, 0x64, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x30, 0x07, 0x21, 0x89, 0x24, 0xb1, 0x81, 0xcd, 0x32, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x65, 0x0e, 0xc3, 0x95, 0x61, 0x00, 0x00, 0x00,
}
