// Code generated by protoc-gen-gogo.
// source: executor.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	executor.proto

It has these top-level messages:
	ExecutorTaskData
*/
package protos

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ExecutorTaskData_Store int32

const (
	ExecutorTaskData_Cassandra ExecutorTaskData_Store = 0
)

var ExecutorTaskData_Store_name = map[int32]string{
	0: "Cassandra",
}
var ExecutorTaskData_Store_value = map[string]int32{
	"Cassandra": 0,
}

func (x ExecutorTaskData_Store) String() string {
	return proto.EnumName(ExecutorTaskData_Store_name, int32(x))
}
func (ExecutorTaskData_Store) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorExecutor, []int{0, 0}
}

type ExecutorTaskData_Algorithm int32

const (
	ExecutorTaskData_ShortestPath ExecutorTaskData_Algorithm = 0
)

var ExecutorTaskData_Algorithm_name = map[int32]string{
	0: "ShortestPath",
}
var ExecutorTaskData_Algorithm_value = map[string]int32{
	"ShortestPath": 0,
}

func (x ExecutorTaskData_Algorithm) String() string {
	return proto.EnumName(ExecutorTaskData_Algorithm_name, int32(x))
}
func (ExecutorTaskData_Algorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorExecutor, []int{0, 1}
}

type ExecutorTaskData struct {
	JobId           string                     `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Superstep       int32                      `protobuf:"varint,2,opt,name=superstep,proto3" json:"superstep,omitempty"`
	Store           ExecutorTaskData_Store     `protobuf:"varint,3,opt,name=store,proto3,enum=protos.ExecutorTaskData_Store" json:"store,omitempty"`
	StoreParams     []byte                     `protobuf:"bytes,4,opt,name=storeParams,proto3" json:"storeParams,omitempty"`
	Algorithm       ExecutorTaskData_Algorithm `protobuf:"varint,5,opt,name=algorithm,proto3,enum=protos.ExecutorTaskData_Algorithm" json:"algorithm,omitempty"`
	AlgorithmParams []byte                     `protobuf:"bytes,6,opt,name=algorithmParams,proto3" json:"algorithmParams,omitempty"`
	ProcessRange    []byte                     `protobuf:"bytes,7,opt,name=processRange,proto3" json:"processRange,omitempty"`
}

func (m *ExecutorTaskData) Reset()                    { *m = ExecutorTaskData{} }
func (m *ExecutorTaskData) String() string            { return proto.CompactTextString(m) }
func (*ExecutorTaskData) ProtoMessage()               {}
func (*ExecutorTaskData) Descriptor() ([]byte, []int) { return fileDescriptorExecutor, []int{0} }

func (m *ExecutorTaskData) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ExecutorTaskData) GetSuperstep() int32 {
	if m != nil {
		return m.Superstep
	}
	return 0
}

func (m *ExecutorTaskData) GetStore() ExecutorTaskData_Store {
	if m != nil {
		return m.Store
	}
	return ExecutorTaskData_Cassandra
}

func (m *ExecutorTaskData) GetStoreParams() []byte {
	if m != nil {
		return m.StoreParams
	}
	return nil
}

func (m *ExecutorTaskData) GetAlgorithm() ExecutorTaskData_Algorithm {
	if m != nil {
		return m.Algorithm
	}
	return ExecutorTaskData_ShortestPath
}

func (m *ExecutorTaskData) GetAlgorithmParams() []byte {
	if m != nil {
		return m.AlgorithmParams
	}
	return nil
}

func (m *ExecutorTaskData) GetProcessRange() []byte {
	if m != nil {
		return m.ProcessRange
	}
	return nil
}

func init() {
	proto.RegisterType((*ExecutorTaskData)(nil), "protos.ExecutorTaskData")
	proto.RegisterEnum("protos.ExecutorTaskData_Store", ExecutorTaskData_Store_name, ExecutorTaskData_Store_value)
	proto.RegisterEnum("protos.ExecutorTaskData_Algorithm", ExecutorTaskData_Algorithm_name, ExecutorTaskData_Algorithm_value)
}

func init() { proto.RegisterFile("executor.proto", fileDescriptorExecutor) }

var fileDescriptorExecutor = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4e, 0x02, 0x31,
	0x10, 0xc6, 0x59, 0xb4, 0x98, 0x8e, 0x2b, 0x6e, 0x26, 0xc6, 0xf4, 0xa0, 0xa6, 0xe9, 0xa9, 0xa7,
	0x3d, 0xa8, 0x0f, 0xa0, 0x51, 0x0f, 0xde, 0x48, 0xf1, 0x05, 0x06, 0x68, 0x58, 0xff, 0x40, 0x37,
	0x9d, 0x92, 0xf8, 0xc2, 0xbe, 0x87, 0xb1, 0x8b, 0xa0, 0x24, 0x9c, 0xda, 0xf9, 0xfa, 0xeb, 0xf7,
	0x4b, 0x0b, 0x43, 0xff, 0xe9, 0xa7, 0xab, 0x14, 0x62, 0xdd, 0xc6, 0x90, 0x02, 0x0e, 0xf2, 0xc2,
	0xe6, 0xab, 0x0f, 0xd5, 0xd3, 0xfa, 0xe8, 0x85, 0xf8, 0xfd, 0x91, 0x12, 0xe1, 0x19, 0x88, 0xb7,
	0x30, 0x79, 0x9e, 0xa9, 0x42, 0x17, 0x56, 0xba, 0x6e, 0xc0, 0x0b, 0x90, 0xbc, 0x6a, 0x7d, 0xe4,
	0xe4, 0x5b, 0xd5, 0xd7, 0x85, 0x15, 0x6e, 0x1b, 0xe0, 0x2d, 0x08, 0x4e, 0x21, 0x7a, 0x75, 0xa0,
	0x0b, 0x3b, 0xbc, 0xbe, 0xea, 0x3c, 0x5c, 0xef, 0x96, 0xd7, 0xe3, 0x1f, 0xca, 0x75, 0x30, 0x6a,
	0x38, 0xce, 0x9b, 0x11, 0x45, 0x5a, 0xb0, 0x3a, 0xd4, 0x85, 0x2d, 0xdd, 0xdf, 0x08, 0xef, 0x40,
	0xd2, 0xc7, 0x3c, 0xc4, 0xd7, 0xd4, 0x2c, 0x94, 0xc8, 0xdd, 0x66, 0x6f, 0xf7, 0xfd, 0x2f, 0xe9,
	0xb6, 0x97, 0xd0, 0xc2, 0xe9, 0x66, 0x58, 0x7b, 0x06, 0xd9, 0xb3, 0x1b, 0xa3, 0x81, 0xb2, 0x8d,
	0x61, 0xea, 0x99, 0x1d, 0x2d, 0xe7, 0x5e, 0x1d, 0x65, 0xec, 0x5f, 0x66, 0xce, 0x41, 0xe4, 0x17,
	0xe0, 0x09, 0xc8, 0x07, 0x62, 0xa6, 0xe5, 0x2c, 0x52, 0xd5, 0x33, 0x97, 0x20, 0x37, 0x76, 0xac,
	0xa0, 0x1c, 0x37, 0x21, 0x26, 0xcf, 0x69, 0x44, 0xa9, 0xa9, 0x7a, 0x93, 0xee, 0xbf, 0x6f, 0xbe,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x09, 0xd4, 0xea, 0x88, 0x01, 0x00, 0x00,
}
