// Code generated by protoc-gen-gogo.
// source: private.proto
// DO NOT EDIT!

package protos

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ExecTaskParams struct {
	TaskId          string               `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	JobId           string               `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Store           string               `protobuf:"bytes,3,opt,name=store,proto3" json:"store,omitempty"`
	StoreParams     []byte               `protobuf:"bytes,4,opt,name=storeParams,proto3" json:"storeParams,omitempty"`
	Algorithm       string               `protobuf:"bytes,5,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	AlgorithmParams []byte               `protobuf:"bytes,6,opt,name=algorithmParams,proto3" json:"algorithmParams,omitempty"`
	SuperstepParams *ExecSuperstepParams `protobuf:"bytes,7,opt,name=superstepParams" json:"superstepParams,omitempty"`
}

func (m *ExecTaskParams) Reset()                    { *m = ExecTaskParams{} }
func (m *ExecTaskParams) String() string            { return proto.CompactTextString(m) }
func (*ExecTaskParams) ProtoMessage()               {}
func (*ExecTaskParams) Descriptor() ([]byte, []int) { return fileDescriptorPrivate, []int{0} }

func (m *ExecTaskParams) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ExecTaskParams) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ExecTaskParams) GetStore() string {
	if m != nil {
		return m.Store
	}
	return ""
}

func (m *ExecTaskParams) GetStoreParams() []byte {
	if m != nil {
		return m.StoreParams
	}
	return nil
}

func (m *ExecTaskParams) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *ExecTaskParams) GetAlgorithmParams() []byte {
	if m != nil {
		return m.AlgorithmParams
	}
	return nil
}

func (m *ExecTaskParams) GetSuperstepParams() *ExecSuperstepParams {
	if m != nil {
		return m.SuperstepParams
	}
	return nil
}

type ExecTaskResult struct {
	TaskId          string               `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	JobId           string               `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	SuperstepResult *ExecSuperstepResult `protobuf:"bytes,3,opt,name=superstepResult" json:"superstepResult,omitempty"`
}

func (m *ExecTaskResult) Reset()                    { *m = ExecTaskResult{} }
func (m *ExecTaskResult) String() string            { return proto.CompactTextString(m) }
func (*ExecTaskResult) ProtoMessage()               {}
func (*ExecTaskResult) Descriptor() ([]byte, []int) { return fileDescriptorPrivate, []int{1} }

func (m *ExecTaskResult) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ExecTaskResult) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *ExecTaskResult) GetSuperstepResult() *ExecSuperstepResult {
	if m != nil {
		return m.SuperstepResult
	}
	return nil
}

type ExecSuperstepParams struct {
	Superstep   int32         `protobuf:"varint,1,opt,name=superstep,proto3" json:"superstep,omitempty"`
	VertexRange []byte        `protobuf:"bytes,2,opt,name=vertexRange,proto3" json:"vertexRange,omitempty"`
	Aggregators []*Aggregator `protobuf:"bytes,3,rep,name=aggregators" json:"aggregators,omitempty"`
}

func (m *ExecSuperstepParams) Reset()                    { *m = ExecSuperstepParams{} }
func (m *ExecSuperstepParams) String() string            { return proto.CompactTextString(m) }
func (*ExecSuperstepParams) ProtoMessage()               {}
func (*ExecSuperstepParams) Descriptor() ([]byte, []int) { return fileDescriptorPrivate, []int{2} }

func (m *ExecSuperstepParams) GetSuperstep() int32 {
	if m != nil {
		return m.Superstep
	}
	return 0
}

func (m *ExecSuperstepParams) GetVertexRange() []byte {
	if m != nil {
		return m.VertexRange
	}
	return nil
}

func (m *ExecSuperstepParams) GetAggregators() []*Aggregator {
	if m != nil {
		return m.Aggregators
	}
	return nil
}

type ExecSuperstepResult struct {
	Aggregators []*Aggregator `protobuf:"bytes,1,rep,name=aggregators" json:"aggregators,omitempty"`
	Stats       *Stats        `protobuf:"bytes,2,opt,name=stats" json:"stats,omitempty"`
}

func (m *ExecSuperstepResult) Reset()                    { *m = ExecSuperstepResult{} }
func (m *ExecSuperstepResult) String() string            { return proto.CompactTextString(m) }
func (*ExecSuperstepResult) ProtoMessage()               {}
func (*ExecSuperstepResult) Descriptor() ([]byte, []int) { return fileDescriptorPrivate, []int{3} }

func (m *ExecSuperstepResult) GetAggregators() []*Aggregator {
	if m != nil {
		return m.Aggregators
	}
	return nil
}

func (m *ExecSuperstepResult) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type Aggregator struct {
	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Value []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Aggregator) Reset()                    { *m = Aggregator{} }
func (m *Aggregator) String() string            { return proto.CompactTextString(m) }
func (*Aggregator) ProtoMessage()               {}
func (*Aggregator) Descriptor() ([]byte, []int) { return fileDescriptorPrivate, []int{4} }

func (m *Aggregator) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Aggregator) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Aggregator) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type JobCheckpoint struct {
	Ranges              []*JobCheckpoint_Range   `protobuf:"bytes,1,rep,name=ranges" json:"ranges,omitempty"`
	Hosts               []*JobCheckpoint_Host    `protobuf:"bytes,2,rep,name=hosts" json:"hosts,omitempty"`
	Tasks               []*JobCheckpoint_Task    `protobuf:"bytes,3,rep,name=tasks" json:"tasks,omitempty"`
	Superstep           *JobCheckpoint_Superstep `protobuf:"bytes,4,opt,name=superstep" json:"superstep,omitempty"`
	PreviousAggregators []*Aggregator            `protobuf:"bytes,5,rep,name=previousAggregators" json:"previousAggregators,omitempty"`
	TotalStats          *Stats                   `protobuf:"bytes,6,opt,name=totalStats" json:"totalStats,omitempty"`
}

func (m *JobCheckpoint) Reset()                    { *m = JobCheckpoint{} }
func (m *JobCheckpoint) String() string            { return proto.CompactTextString(m) }
func (*JobCheckpoint) ProtoMessage()               {}
func (*JobCheckpoint) Descriptor() ([]byte, []int) { return fileDescriptorPrivate, []int{5} }

func (m *JobCheckpoint) GetRanges() []*JobCheckpoint_Range {
	if m != nil {
		return m.Ranges
	}
	return nil
}

func (m *JobCheckpoint) GetHosts() []*JobCheckpoint_Host {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *JobCheckpoint) GetTasks() []*JobCheckpoint_Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *JobCheckpoint) GetSuperstep() *JobCheckpoint_Superstep {
	if m != nil {
		return m.Superstep
	}
	return nil
}

func (m *JobCheckpoint) GetPreviousAggregators() []*Aggregator {
	if m != nil {
		return m.PreviousAggregators
	}
	return nil
}

func (m *JobCheckpoint) GetTotalStats() *Stats {
	if m != nil {
		return m.TotalStats
	}
	return nil
}

type JobCheckpoint_Range struct {
	Id          int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VertexRange []byte  `protobuf:"bytes,2,opt,name=vertexRange,proto3" json:"vertexRange,omitempty"`
	Hosts       []int32 `protobuf:"varint,3,rep,packed,name=hosts" json:"hosts,omitempty"`
}

func (m *JobCheckpoint_Range) Reset()                    { *m = JobCheckpoint_Range{} }
func (m *JobCheckpoint_Range) String() string            { return proto.CompactTextString(m) }
func (*JobCheckpoint_Range) ProtoMessage()               {}
func (*JobCheckpoint_Range) Descriptor() ([]byte, []int) { return fileDescriptorPrivate, []int{5, 0} }

func (m *JobCheckpoint_Range) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JobCheckpoint_Range) GetVertexRange() []byte {
	if m != nil {
		return m.VertexRange
	}
	return nil
}

func (m *JobCheckpoint_Range) GetHosts() []int32 {
	if m != nil {
		return m.Hosts
	}
	return nil
}

type JobCheckpoint_Host struct {
	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname  string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	FailCount int32  `protobuf:"varint,3,opt,name=failCount,proto3" json:"failCount,omitempty"`
}

func (m *JobCheckpoint_Host) Reset()                    { *m = JobCheckpoint_Host{} }
func (m *JobCheckpoint_Host) String() string            { return proto.CompactTextString(m) }
func (*JobCheckpoint_Host) ProtoMessage()               {}
func (*JobCheckpoint_Host) Descriptor() ([]byte, []int) { return fileDescriptorPrivate, []int{5, 1} }

func (m *JobCheckpoint_Host) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *JobCheckpoint_Host) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *JobCheckpoint_Host) GetFailCount() int32 {
	if m != nil {
		return m.FailCount
	}
	return 0
}

type JobCheckpoint_Task struct {
	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RangeId   int32  `protobuf:"varint,2,opt,name=rangeId,proto3" json:"rangeId,omitempty"`
	HostId    int32  `protobuf:"varint,3,opt,name=hostId,proto3" json:"hostId,omitempty"`
	StartTime int64  `protobuf:"varint,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
}

func (m *JobCheckpoint_Task) Reset()                    { *m = JobCheckpoint_Task{} }
func (m *JobCheckpoint_Task) String() string            { return proto.CompactTextString(m) }
func (*JobCheckpoint_Task) ProtoMessage()               {}
func (*JobCheckpoint_Task) Descriptor() ([]byte, []int) { return fileDescriptorPrivate, []int{5, 2} }

func (m *JobCheckpoint_Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JobCheckpoint_Task) GetRangeId() int32 {
	if m != nil {
		return m.RangeId
	}
	return 0
}

func (m *JobCheckpoint_Task) GetHostId() int32 {
	if m != nil {
		return m.HostId
	}
	return 0
}

func (m *JobCheckpoint_Task) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

type JobCheckpoint_Superstep struct {
	Number      int32         `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Aggregators []*Aggregator `protobuf:"bytes,2,rep,name=aggregators" json:"aggregators,omitempty"`
	Completed   []int32       `protobuf:"varint,3,rep,packed,name=completed" json:"completed,omitempty"`
	Stats       *Stats        `protobuf:"bytes,4,opt,name=stats" json:"stats,omitempty"`
}

func (m *JobCheckpoint_Superstep) Reset()         { *m = JobCheckpoint_Superstep{} }
func (m *JobCheckpoint_Superstep) String() string { return proto.CompactTextString(m) }
func (*JobCheckpoint_Superstep) ProtoMessage()    {}
func (*JobCheckpoint_Superstep) Descriptor() ([]byte, []int) {
	return fileDescriptorPrivate, []int{5, 3}
}

func (m *JobCheckpoint_Superstep) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *JobCheckpoint_Superstep) GetAggregators() []*Aggregator {
	if m != nil {
		return m.Aggregators
	}
	return nil
}

func (m *JobCheckpoint_Superstep) GetCompleted() []int32 {
	if m != nil {
		return m.Completed
	}
	return nil
}

func (m *JobCheckpoint_Superstep) GetStats() *Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*ExecTaskParams)(nil), "protos.ExecTaskParams")
	proto.RegisterType((*ExecTaskResult)(nil), "protos.ExecTaskResult")
	proto.RegisterType((*ExecSuperstepParams)(nil), "protos.ExecSuperstepParams")
	proto.RegisterType((*ExecSuperstepResult)(nil), "protos.ExecSuperstepResult")
	proto.RegisterType((*Aggregator)(nil), "protos.Aggregator")
	proto.RegisterType((*JobCheckpoint)(nil), "protos.JobCheckpoint")
	proto.RegisterType((*JobCheckpoint_Range)(nil), "protos.JobCheckpoint.Range")
	proto.RegisterType((*JobCheckpoint_Host)(nil), "protos.JobCheckpoint.Host")
	proto.RegisterType((*JobCheckpoint_Task)(nil), "protos.JobCheckpoint.Task")
	proto.RegisterType((*JobCheckpoint_Superstep)(nil), "protos.JobCheckpoint.Superstep")
}

func init() { proto.RegisterFile("private.proto", fileDescriptorPrivate) }

var fileDescriptorPrivate = []byte{
	// 601 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0x95, 0xc1, 0x26, 0x3f, 0x86, 0x90, 0x48, 0x9b, 0xe8, 0x27, 0xcb, 0x8d, 0x54, 0xe4, 0x5e,
	0xb8, 0x14, 0x55, 0xa4, 0xd7, 0x1e, 0xa2, 0x34, 0x55, 0xe9, 0xa5, 0xd1, 0x26, 0x5f, 0x60, 0x81,
	0x0d, 0xb8, 0xd8, 0xac, 0xb5, 0xbb, 0x46, 0xf9, 0x02, 0xe9, 0xa5, 0x5f, 0xa1, 0x1f, 0xb6, 0xda,
	0xd9, 0xf5, 0x9f, 0x38, 0xa0, 0xa6, 0x27, 0x3c, 0xcf, 0x6f, 0x9e, 0xc6, 0xef, 0xcd, 0x00, 0xc3,
	0x5c, 0x26, 0x3b, 0xa6, 0xf9, 0x24, 0x97, 0x42, 0x0b, 0xd2, 0xc3, 0x1f, 0x15, 0x0d, 0x15, 0x97,
	0xbb, 0x64, 0xe1, 0xe0, 0xf8, 0xa9, 0x03, 0x27, 0x37, 0x8f, 0x7c, 0x71, 0xcf, 0xd4, 0xe6, 0x96,
	0x49, 0x96, 0x29, 0xf2, 0x3f, 0xf4, 0x34, 0x53, 0x9b, 0xd9, 0x32, 0xf4, 0x46, 0xde, 0xb8, 0x4f,
	0x5d, 0x45, 0xce, 0x21, 0xf8, 0x21, 0xe6, 0xb3, 0x65, 0xd8, 0x41, 0xd8, 0x16, 0x06, 0x55, 0x5a,
	0x48, 0x1e, 0x76, 0x2d, 0x8a, 0x05, 0x19, 0xc1, 0x00, 0x1f, 0xac, 0x64, 0xe8, 0x8f, 0xbc, 0xf1,
	0x31, 0x6d, 0x42, 0xe4, 0x02, 0xfa, 0x2c, 0x5d, 0x09, 0x99, 0xe8, 0x75, 0x16, 0x06, 0xd8, 0x5b,
	0x03, 0x64, 0x0c, 0xa7, 0x55, 0xe1, 0x34, 0x7a, 0xa8, 0xd1, 0x86, 0xc9, 0x0d, 0x9c, 0xaa, 0x22,
	0xe7, 0x52, 0x69, 0x9e, 0x3b, 0xe6, 0xd1, 0xc8, 0x1b, 0x0f, 0xa6, 0x6f, 0xec, 0x17, 0xaa, 0x89,
	0xf9, 0xbc, 0xbb, 0xe7, 0x14, 0xda, 0xee, 0x89, 0x9f, 0xbc, 0xda, 0x07, 0xca, 0x55, 0x91, 0xea,
	0x7f, 0xf4, 0xa1, 0x39, 0x87, 0x15, 0x40, 0x47, 0x0e, 0xcd, 0x61, 0x29, 0xb4, 0xdd, 0x13, 0xff,
	0xf2, 0xe0, 0x6c, 0xcf, 0xc0, 0xc6, 0xae, 0x8a, 0x8a, 0xf3, 0x04, 0xb4, 0x06, 0x8c, 0xdd, 0x3b,
	0x2e, 0x35, 0x7f, 0xa4, 0x6c, 0xbb, 0xe2, 0x38, 0xd8, 0x31, 0x6d, 0x42, 0xe4, 0x23, 0x0c, 0xd8,
	0x6a, 0x25, 0xf9, 0x8a, 0x69, 0x21, 0x55, 0xd8, 0x1d, 0x75, 0xc7, 0x83, 0x29, 0x29, 0x47, 0xbb,
	0xaa, 0x5e, 0xd1, 0x26, 0x2d, 0xce, 0x5b, 0xc3, 0x38, 0x67, 0x5a, 0x62, 0xde, 0xab, 0xc4, 0xc8,
	0x3b, 0xb3, 0x29, 0x4c, 0x2b, 0x1c, 0x6f, 0x30, 0x1d, 0x96, 0xfc, 0x3b, 0x03, 0x52, 0xfb, 0x2e,
	0xfe, 0x02, 0x50, 0xf7, 0x13, 0x02, 0xfe, 0x96, 0x65, 0xdc, 0x05, 0x80, 0xcf, 0xe4, 0x04, 0x3a,
	0x49, 0xe9, 0x7d, 0x27, 0xc1, 0x38, 0x76, 0x2c, 0x2d, 0xec, 0x02, 0x1e, 0x53, 0x5b, 0xc4, 0x3f,
	0x7b, 0x30, 0xfc, 0x26, 0xe6, 0xd7, 0x6b, 0xbe, 0xd8, 0xe4, 0x22, 0xd9, 0x6a, 0x72, 0x09, 0x3d,
	0x69, 0xac, 0x28, 0xe7, 0xad, 0x72, 0x79, 0x46, 0x9b, 0xa0, 0x5d, 0xd4, 0x51, 0xc9, 0x07, 0x08,
	0xd6, 0x42, 0xe1, 0xcc, 0xa6, 0x27, 0xda, 0xdf, 0xf3, 0x55, 0x28, 0x4d, 0x2d, 0xd1, 0x74, 0x98,
	0x3d, 0x29, 0x2d, 0x3e, 0xd0, 0x81, 0x6b, 0x66, 0x89, 0xe4, 0x53, 0x33, 0x5a, 0x1f, 0xbd, 0x79,
	0xbb, 0xbf, 0xab, 0xce, 0xa1, 0x91, 0xfd, 0x67, 0x38, 0xcb, 0x25, 0xdf, 0x25, 0xa2, 0x50, 0x57,
	0x8d, 0x50, 0x82, 0x83, 0xa1, 0xec, 0xa3, 0x93, 0xf7, 0x00, 0x5a, 0x68, 0x96, 0x62, 0x18, 0x78,
	0x6b, 0x2f, 0x12, 0x6a, 0x10, 0xa2, 0xef, 0x10, 0xd8, 0xbd, 0xb2, 0x69, 0xd8, 0x85, 0x34, 0x69,
	0xfc, 0x7d, 0x13, 0xcf, 0x4b, 0x4b, 0x8d, 0x41, 0x81, 0xb3, 0x2d, 0xba, 0x05, 0xdf, 0xb8, 0xf8,
	0x42, 0x2f, 0x82, 0xff, 0x0c, 0x01, 0xb7, 0xc0, 0x66, 0x5e, 0xd5, 0xe6, 0x26, 0x1e, 0x58, 0x92,
	0x5e, 0x8b, 0x62, 0x6b, 0x8f, 0x2d, 0xa0, 0x35, 0x10, 0x3d, 0x80, 0x6f, 0x5c, 0x6e, 0x28, 0xda,
	0x7d, 0x09, 0xe1, 0x08, 0xc3, 0x75, 0x07, 0x1c, 0xd0, 0xb2, 0x34, 0x07, 0x6f, 0xb4, 0x67, 0x4b,
	0x27, 0xe6, 0x2a, 0xbc, 0x3d, 0xcd, 0xa4, 0xbe, 0x4f, 0x32, 0x8e, 0x01, 0x75, 0x69, 0x0d, 0x44,
	0xbf, 0x3d, 0xe8, 0x57, 0xc1, 0x18, 0x8d, 0x6d, 0x91, 0xcd, 0xb9, 0x74, 0xdf, 0xe0, 0xaa, 0xf6,
	0xc9, 0x74, 0x5e, 0x77, 0x32, 0x17, 0xd0, 0x5f, 0x88, 0x2c, 0x4f, 0xb9, 0xe6, 0x4b, 0xe7, 0x57,
	0x0d, 0xd4, 0x07, 0xe5, 0x1f, 0x3e, 0xa8, 0xb9, 0xfd, 0xdf, 0xbf, 0xfc, 0x13, 0x00, 0x00, 0xff,
	0xff, 0x0f, 0xcd, 0xa7, 0xb7, 0x0f, 0x06, 0x00, 0x00,
}
