// Code generated by protoc-gen-gogo.
// source: store.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	store.proto

It has these top-level messages:
	CassandraStoreParams
	CassandraTokenRange
*/
package protos

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CassandraStoreParams struct {
	Hosts             []string                           `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
	Keyspace          string                             `protobuf:"bytes,2,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	ReplicationFactor int32                              `protobuf:"varint,3,opt,name=replicationFactor,proto3" json:"replicationFactor,omitempty"`
	VerticesTable     string                             `protobuf:"bytes,4,opt,name=verticesTable,proto3" json:"verticesTable,omitempty"`
	EdgesTable        string                             `protobuf:"bytes,5,opt,name=edgesTable,proto3" json:"edgesTable,omitempty"`
	BatchOptions      *CassandraStoreParams_BatchOptions `protobuf:"bytes,6,opt,name=batchOptions" json:"batchOptions,omitempty"`
	Timeout           int32                              `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
}

func (m *CassandraStoreParams) Reset()                    { *m = CassandraStoreParams{} }
func (m *CassandraStoreParams) String() string            { return proto.CompactTextString(m) }
func (*CassandraStoreParams) ProtoMessage()               {}
func (*CassandraStoreParams) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{0} }

func (m *CassandraStoreParams) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *CassandraStoreParams) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *CassandraStoreParams) GetReplicationFactor() int32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

func (m *CassandraStoreParams) GetVerticesTable() string {
	if m != nil {
		return m.VerticesTable
	}
	return ""
}

func (m *CassandraStoreParams) GetEdgesTable() string {
	if m != nil {
		return m.EdgesTable
	}
	return ""
}

func (m *CassandraStoreParams) GetBatchOptions() *CassandraStoreParams_BatchOptions {
	if m != nil {
		return m.BatchOptions
	}
	return nil
}

func (m *CassandraStoreParams) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type CassandraStoreParams_BatchOptions struct {
	MaxSize  int32 `protobuf:"varint,1,opt,name=MaxSize,proto3" json:"MaxSize,omitempty"`
	MaxBytes int32 `protobuf:"varint,2,opt,name=MaxBytes,proto3" json:"MaxBytes,omitempty"`
}

func (m *CassandraStoreParams_BatchOptions) Reset()         { *m = CassandraStoreParams_BatchOptions{} }
func (m *CassandraStoreParams_BatchOptions) String() string { return proto.CompactTextString(m) }
func (*CassandraStoreParams_BatchOptions) ProtoMessage()    {}
func (*CassandraStoreParams_BatchOptions) Descriptor() ([]byte, []int) {
	return fileDescriptorStore, []int{0, 0}
}

func (m *CassandraStoreParams_BatchOptions) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *CassandraStoreParams_BatchOptions) GetMaxBytes() int32 {
	if m != nil {
		return m.MaxBytes
	}
	return 0
}

type CassandraTokenRange struct {
	Partitioner string `protobuf:"bytes,1,opt,name=partitioner,proto3" json:"partitioner,omitempty"`
	StartToken  string `protobuf:"bytes,2,opt,name=startToken,proto3" json:"startToken,omitempty"`
	EndToken    string `protobuf:"bytes,3,opt,name=endToken,proto3" json:"endToken,omitempty"`
}

func (m *CassandraTokenRange) Reset()                    { *m = CassandraTokenRange{} }
func (m *CassandraTokenRange) String() string            { return proto.CompactTextString(m) }
func (*CassandraTokenRange) ProtoMessage()               {}
func (*CassandraTokenRange) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{1} }

func (m *CassandraTokenRange) GetPartitioner() string {
	if m != nil {
		return m.Partitioner
	}
	return ""
}

func (m *CassandraTokenRange) GetStartToken() string {
	if m != nil {
		return m.StartToken
	}
	return ""
}

func (m *CassandraTokenRange) GetEndToken() string {
	if m != nil {
		return m.EndToken
	}
	return ""
}

func init() {
	proto.RegisterType((*CassandraStoreParams)(nil), "protos.CassandraStoreParams")
	proto.RegisterType((*CassandraStoreParams_BatchOptions)(nil), "protos.CassandraStoreParams.BatchOptions")
	proto.RegisterType((*CassandraTokenRange)(nil), "protos.CassandraTokenRange")
}

func init() { proto.RegisterFile("store.proto", fileDescriptorStore) }

var fileDescriptorStore = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0x4d, 0xc1, 0x82, 0x0c, 0x78, 0x70, 0xe5, 0xb0, 0xe1, 0x60, 0x1a, 0xe2, 0xa1, 0x26, 0x86,
	0x83, 0xfe, 0x01, 0x1a, 0x6f, 0x44, 0xb3, 0xf0, 0x03, 0x43, 0x99, 0x40, 0x03, 0x74, 0x9b, 0x9d,
	0xd1, 0x80, 0xbf, 0xec, 0x4f, 0x98, 0xee, 0x02, 0x29, 0xea, 0x69, 0xf3, 0xde, 0xbc, 0x79, 0x3b,
	0xf3, 0x06, 0xba, 0x2c, 0xd6, 0xd1, 0xa8, 0x74, 0x56, 0xac, 0x6a, 0xf9, 0x87, 0x87, 0xdf, 0x0d,
	0xe8, 0x3f, 0x23, 0x33, 0x16, 0x0b, 0x87, 0xd3, 0x4a, 0xf0, 0x8e, 0x0e, 0xb7, 0xac, 0xfa, 0x10,
	0xaf, 0x2c, 0x0b, 0xeb, 0x28, 0x69, 0xa6, 0x1d, 0x13, 0x80, 0x1a, 0xc0, 0xe5, 0x9a, 0xf6, 0x5c,
	0x62, 0x46, 0xba, 0x91, 0x44, 0x69, 0xc7, 0x9c, 0xb0, 0x7a, 0x80, 0x6b, 0x47, 0xe5, 0x26, 0xcf,
	0x50, 0x72, 0x5b, 0xbc, 0x62, 0x26, 0xd6, 0xe9, 0x66, 0x12, 0xa5, 0xb1, 0xf9, 0x5b, 0x50, 0x77,
	0x70, 0xf5, 0x49, 0x4e, 0xf2, 0x8c, 0x78, 0x86, 0xf3, 0x0d, 0xe9, 0x0b, 0x6f, 0x77, 0x4e, 0xaa,
	0x5b, 0x00, 0x5a, 0x2c, 0x8f, 0x92, 0xd8, 0x4b, 0x6a, 0x8c, 0x9a, 0x40, 0x6f, 0x8e, 0x92, 0xad,
	0xde, 0xca, 0xca, 0x9a, 0x75, 0x2b, 0x89, 0xd2, 0xee, 0xe3, 0x7d, 0x58, 0x92, 0x47, 0xff, 0x6d,
	0x36, 0x1a, 0xd7, 0x1a, 0xcc, 0x59, 0xbb, 0xd2, 0xd0, 0x96, 0x7c, 0x4b, 0xf6, 0x43, 0x74, 0xdb,
	0x0f, 0x7e, 0x84, 0x83, 0x17, 0xe8, 0x8d, 0x7f, 0x29, 0x27, 0xb8, 0x9b, 0xe6, 0x5f, 0xa4, 0xa3,
	0xa0, 0x3c, 0xc0, 0x2a, 0xa2, 0x09, 0xee, 0xc6, 0x7b, 0x21, 0xf6, 0x11, 0xc5, 0xe6, 0x84, 0x87,
	0x0c, 0x37, 0xa7, 0x91, 0x66, 0x76, 0x4d, 0x85, 0xc1, 0x62, 0x49, 0x2a, 0x81, 0x6e, 0x89, 0x4e,
	0xf2, 0xca, 0x9a, 0x9c, 0x37, 0xec, 0x98, 0x3a, 0x55, 0xe5, 0xc0, 0x82, 0x4e, 0x7c, 0xd3, 0x21,
	0xf9, 0x1a, 0x53, 0x7d, 0x4a, 0xc5, 0x22, 0x54, 0x9b, 0xe1, 0x2e, 0x47, 0x3c, 0x0f, 0xa7, 0x7e,
	0xfa, 0x09, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xaa, 0xbd, 0x12, 0x00, 0x02, 0x00, 0x00,
}
