// Code generated by protoc-gen-gogo.
// source: store.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	store.proto

It has these top-level messages:
	CassandraStoreParams
	Int32Value
*/
package protos

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CassandraStoreParams struct {
	Hosts         []string                           `protobuf:"bytes,1,rep,name=hosts" json:"hosts,omitempty"`
	Keyspace      string                             `protobuf:"bytes,2,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	VerticesTable string                             `protobuf:"bytes,3,opt,name=verticesTable,proto3" json:"verticesTable,omitempty"`
	EdgesTable    string                             `protobuf:"bytes,4,opt,name=edgesTable,proto3" json:"edgesTable,omitempty"`
	BatchOptions  *CassandraStoreParams_BatchOptions `protobuf:"bytes,5,opt,name=batchOptions" json:"batchOptions,omitempty"`
}

func (m *CassandraStoreParams) Reset()                    { *m = CassandraStoreParams{} }
func (m *CassandraStoreParams) String() string            { return proto.CompactTextString(m) }
func (*CassandraStoreParams) ProtoMessage()               {}
func (*CassandraStoreParams) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{0} }

func (m *CassandraStoreParams) GetHosts() []string {
	if m != nil {
		return m.Hosts
	}
	return nil
}

func (m *CassandraStoreParams) GetKeyspace() string {
	if m != nil {
		return m.Keyspace
	}
	return ""
}

func (m *CassandraStoreParams) GetVerticesTable() string {
	if m != nil {
		return m.VerticesTable
	}
	return ""
}

func (m *CassandraStoreParams) GetEdgesTable() string {
	if m != nil {
		return m.EdgesTable
	}
	return ""
}

func (m *CassandraStoreParams) GetBatchOptions() *CassandraStoreParams_BatchOptions {
	if m != nil {
		return m.BatchOptions
	}
	return nil
}

type CassandraStoreParams_BatchOptions struct {
	MaxSize  int32 `protobuf:"varint,1,opt,name=MaxSize,proto3" json:"MaxSize,omitempty"`
	MaxBytes int32 `protobuf:"varint,2,opt,name=MaxBytes,proto3" json:"MaxBytes,omitempty"`
}

func (m *CassandraStoreParams_BatchOptions) Reset()         { *m = CassandraStoreParams_BatchOptions{} }
func (m *CassandraStoreParams_BatchOptions) String() string { return proto.CompactTextString(m) }
func (*CassandraStoreParams_BatchOptions) ProtoMessage()    {}
func (*CassandraStoreParams_BatchOptions) Descriptor() ([]byte, []int) {
	return fileDescriptorStore, []int{0, 0}
}

func (m *CassandraStoreParams_BatchOptions) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *CassandraStoreParams_BatchOptions) GetMaxBytes() int32 {
	if m != nil {
		return m.MaxBytes
	}
	return 0
}

type Int32Value struct {
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Int32Value) Reset()                    { *m = Int32Value{} }
func (m *Int32Value) String() string            { return proto.CompactTextString(m) }
func (*Int32Value) ProtoMessage()               {}
func (*Int32Value) Descriptor() ([]byte, []int) { return fileDescriptorStore, []int{1} }

func (m *Int32Value) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*CassandraStoreParams)(nil), "protos.CassandraStoreParams")
	proto.RegisterType((*CassandraStoreParams_BatchOptions)(nil), "protos.CassandraStoreParams.BatchOptions")
	proto.RegisterType((*Int32Value)(nil), "protos.Int32Value")
}

func init() { proto.RegisterFile("store.proto", fileDescriptorStore) }

var fileDescriptorStore = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xe5, 0x96, 0x00, 0xbd, 0x96, 0xc5, 0xea, 0x60, 0x75, 0x40, 0x51, 0xc4, 0x10, 0x96,
	0x0c, 0xed, 0x1b, 0x14, 0x16, 0x86, 0x08, 0xe4, 0x22, 0xf6, 0x4b, 0x7a, 0xa2, 0x11, 0x25, 0x8e,
	0x7c, 0x47, 0xd5, 0xf2, 0x3a, 0xbc, 0x28, 0x4a, 0x4c, 0xab, 0x54, 0x62, 0xb2, 0xbf, 0xf3, 0x77,
	0xd6, 0xdd, 0x0f, 0x63, 0x16, 0xe7, 0x29, 0x6b, 0xbc, 0x13, 0xa7, 0x2f, 0xbb, 0x83, 0x93, 0x9f,
	0x01, 0x4c, 0x1f, 0x90, 0x19, 0xeb, 0xb5, 0xc7, 0x55, 0x2b, 0xbc, 0xa0, 0xc7, 0x4f, 0xd6, 0x53,
	0x88, 0x36, 0x8e, 0x85, 0x8d, 0x8a, 0x87, 0xe9, 0xc8, 0x06, 0xd0, 0x33, 0xb8, 0xfe, 0xa0, 0x03,
	0x37, 0x58, 0x92, 0x19, 0xc4, 0x2a, 0x1d, 0xd9, 0x13, 0xeb, 0x3b, 0xb8, 0xd9, 0x91, 0x97, 0xaa,
	0x24, 0x7e, 0xc5, 0x62, 0x4b, 0x66, 0xd8, 0x09, 0xe7, 0x45, 0x7d, 0x0b, 0x40, 0xeb, 0xf7, 0xa3,
	0x72, 0xd1, 0x29, 0xbd, 0x8a, 0xce, 0x61, 0x52, 0xa0, 0x94, 0x9b, 0xe7, 0x46, 0x2a, 0x57, 0xb3,
	0x89, 0x62, 0x95, 0x8e, 0xe7, 0xf7, 0x61, 0x6c, 0xce, 0xfe, 0x9b, 0x35, 0x5b, 0xf6, 0x1a, 0xec,
	0x59, 0xfb, 0xec, 0x11, 0x26, 0xfd, 0x57, 0x6d, 0xe0, 0x2a, 0xc7, 0xfd, 0xaa, 0xfa, 0x26, 0xa3,
	0x62, 0x95, 0x46, 0xf6, 0x88, 0xed, 0x6a, 0x39, 0xee, 0x97, 0x07, 0x21, 0xee, 0x56, 0x8b, 0xec,
	0x89, 0x93, 0x04, 0xe0, 0xa9, 0x96, 0xc5, 0xfc, 0x0d, 0xb7, 0x5f, 0xd4, 0x46, 0xb3, 0x6b, 0x2f,
	0x7f, 0x3f, 0x04, 0x28, 0x42, 0xa2, 0x8b, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x13, 0x99, 0x85,
	0x12, 0x67, 0x01, 0x00, 0x00,
}
