// Code generated by protoc-gen-gogo.
// source: value.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	value.proto

It has these top-level messages:
	Int32Value
	Int64Value
	StringValue
	StringListValue
	BoolValue
	DimacsCoordinateValue
*/
package protos

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Int32Value struct {
	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Int32Value) Reset()                    { *m = Int32Value{} }
func (m *Int32Value) String() string            { return proto.CompactTextString(m) }
func (*Int32Value) ProtoMessage()               {}
func (*Int32Value) Descriptor() ([]byte, []int) { return fileDescriptorValue, []int{0} }

func (m *Int32Value) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int64Value struct {
	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Int64Value) Reset()                    { *m = Int64Value{} }
func (m *Int64Value) String() string            { return proto.CompactTextString(m) }
func (*Int64Value) ProtoMessage()               {}
func (*Int64Value) Descriptor() ([]byte, []int) { return fileDescriptorValue, []int{1} }

func (m *Int64Value) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type StringValue struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *StringValue) Reset()                    { *m = StringValue{} }
func (m *StringValue) String() string            { return proto.CompactTextString(m) }
func (*StringValue) ProtoMessage()               {}
func (*StringValue) Descriptor() ([]byte, []int) { return fileDescriptorValue, []int{2} }

func (m *StringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type StringListValue struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *StringListValue) Reset()                    { *m = StringListValue{} }
func (m *StringListValue) String() string            { return proto.CompactTextString(m) }
func (*StringListValue) ProtoMessage()               {}
func (*StringListValue) Descriptor() ([]byte, []int) { return fileDescriptorValue, []int{3} }

func (m *StringListValue) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type BoolValue struct {
	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *BoolValue) Reset()                    { *m = BoolValue{} }
func (m *BoolValue) String() string            { return proto.CompactTextString(m) }
func (*BoolValue) ProtoMessage()               {}
func (*BoolValue) Descriptor() ([]byte, []int) { return fileDescriptorValue, []int{4} }

func (m *BoolValue) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type DimacsCoordinateValue struct {
	X int32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (m *DimacsCoordinateValue) Reset()                    { *m = DimacsCoordinateValue{} }
func (m *DimacsCoordinateValue) String() string            { return proto.CompactTextString(m) }
func (*DimacsCoordinateValue) ProtoMessage()               {}
func (*DimacsCoordinateValue) Descriptor() ([]byte, []int) { return fileDescriptorValue, []int{5} }

func (m *DimacsCoordinateValue) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *DimacsCoordinateValue) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Int32Value)(nil), "protos.Int32Value")
	proto.RegisterType((*Int64Value)(nil), "protos.Int64Value")
	proto.RegisterType((*StringValue)(nil), "protos.StringValue")
	proto.RegisterType((*StringListValue)(nil), "protos.StringListValue")
	proto.RegisterType((*BoolValue)(nil), "protos.BoolValue")
	proto.RegisterType((*DimacsCoordinateValue)(nil), "protos.DimacsCoordinateValue")
}

func init() { proto.RegisterFile("value.proto", fileDescriptorValue) }

var fileDescriptorValue = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4b, 0xcc, 0x29,
	0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a, 0x4a, 0x5c, 0x5c,
	0x9e, 0x79, 0x25, 0xc6, 0x46, 0x61, 0x20, 0x39, 0x21, 0x11, 0x2e, 0x56, 0xb0, 0x22, 0x09, 0x46,
	0x05, 0x46, 0x0d, 0xd6, 0x20, 0x08, 0x07, 0xaa, 0xc6, 0xcc, 0x04, 0x8b, 0x1a, 0x66, 0x98, 0x1a,
	0x65, 0x2e, 0xee, 0xe0, 0x92, 0xa2, 0xcc, 0xbc, 0x74, 0x2c, 0x8a, 0x38, 0x61, 0x8a, 0xd4, 0xb9,
	0xf8, 0x21, 0x8a, 0x7c, 0x32, 0x8b, 0x4b, 0x30, 0x14, 0x32, 0x23, 0x14, 0x2a, 0x72, 0x71, 0x3a,
	0xe5, 0xe7, 0xe7, 0x60, 0x31, 0x8b, 0x03, 0xa6, 0xc4, 0x98, 0x4b, 0xd4, 0x25, 0x33, 0x37, 0x31,
	0xb9, 0xd8, 0x39, 0x3f, 0xbf, 0x28, 0x25, 0x33, 0x2f, 0xb1, 0x24, 0x15, 0xa2, 0x9c, 0x87, 0x8b,
	0xb1, 0x02, 0xea, 0x7e, 0xc6, 0x0a, 0x10, 0xaf, 0x52, 0x82, 0x09, 0xc2, 0xab, 0x4c, 0x82, 0xf8,
	0xda, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x34, 0x17, 0x7e, 0x6a, 0x0b, 0x01, 0x00, 0x00,
}
