// Code generated by protoc-gen-gogo.
// source: algorithms.proto
// DO NOT EDIT!

/*
Package algorithms is a generated protocol buffer package.

It is generated from these files:
	algorithms.proto

It has these top-level messages:
	ShortestPathParams
	ShortestPathMessage
*/
package algorithms

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ShortestPathParams struct {
	From string `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
}

func (m *ShortestPathParams) Reset()                    { *m = ShortestPathParams{} }
func (m *ShortestPathParams) String() string            { return proto.CompactTextString(m) }
func (*ShortestPathParams) ProtoMessage()               {}
func (*ShortestPathParams) Descriptor() ([]byte, []int) { return fileDescriptorAlgorithms, []int{0} }

func (m *ShortestPathParams) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *ShortestPathParams) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

type ShortestPathMessage struct {
	PathLength int64 `protobuf:"varint,1,opt,name=pathLength,proto3" json:"pathLength,omitempty"`
}

func (m *ShortestPathMessage) Reset()                    { *m = ShortestPathMessage{} }
func (m *ShortestPathMessage) String() string            { return proto.CompactTextString(m) }
func (*ShortestPathMessage) ProtoMessage()               {}
func (*ShortestPathMessage) Descriptor() ([]byte, []int) { return fileDescriptorAlgorithms, []int{1} }

func (m *ShortestPathMessage) GetPathLength() int64 {
	if m != nil {
		return m.PathLength
	}
	return 0
}

func init() {
	proto.RegisterType((*ShortestPathParams)(nil), "algorithms.ShortestPathParams")
	proto.RegisterType((*ShortestPathMessage)(nil), "algorithms.ShortestPathMessage")
}

func init() { proto.RegisterFile("algorithms.proto", fileDescriptorAlgorithms) }

var fileDescriptorAlgorithms = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x48, 0xcc, 0x49, 0xcf,
	0x2f, 0xca, 0x2c, 0xc9, 0xc8, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x42, 0x88,
	0x28, 0x59, 0x70, 0x09, 0x05, 0x67, 0xe4, 0x17, 0x95, 0xa4, 0x16, 0x97, 0x04, 0x24, 0x96, 0x64,
	0x04, 0x24, 0x16, 0x25, 0xe6, 0x16, 0x0b, 0x09, 0x71, 0xb1, 0xa4, 0x15, 0xe5, 0xe7, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x7c, 0x5c, 0x4c, 0x25, 0xf9, 0x12, 0x4c, 0x60,
	0x11, 0xa6, 0x92, 0x7c, 0x25, 0x53, 0x2e, 0x61, 0x64, 0x9d, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9,
	0xa9, 0x42, 0x72, 0x5c, 0x5c, 0x05, 0x89, 0x25, 0x19, 0x3e, 0xa9, 0x79, 0xe9, 0x25, 0x19, 0x60,
	0x03, 0x98, 0x83, 0x90, 0x44, 0x92, 0xd8, 0xc0, 0x6e, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x82, 0x64, 0x2a, 0x3f, 0x97, 0x00, 0x00, 0x00,
}
